#!/usr/bin/env bash
#
# plans-index.sh — generate .omo/plans/INDEX.md from plan files
#
# Plan: .omo/plans/workflow-standardization.md §4 ulw-plan bullet (W2.3).
#
# Scans .omo/plans/*.md (excluding INDEX.md itself and *.reviews.md ledgers),
# extracts per-plan metadata and writes .omo/plans/INDEX.md as a markdown
# table sorted by mtime (newest first):
#   name | title (first H1) | status (first `Status:` line, if any) |
#   checkboxes done/total | execution-record present | mtime (UTC)
#
# Idempotent: regenerates INDEX.md wholesale on every run (no merge).
# Atomic write (tmp + mv).
#
# Usage:
#   plans-index.sh [<plans_dir>]
#     <plans_dir> defaults to ./.omo/plans (or script-relative repo root).
#
# Exit codes:
#   0  success (INDEX.md written; empty dir also succeeds)
#   1  usage error / internal error
#
# Dependencies: bash >= 4.3, GNU or BSD stat, awk, sort. No network, no ports.

set -euo pipefail

SCRIPT_NAME="$(basename "$0")"

die_usage() {
    echo "usage error: $*" >&2
    exit 1
}

default_plans_dir() {
    local script_dir
    script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    printf '%s/.omo/plans' "$(dirname "$script_dir")"
}

PLANS_DIR="${1:-$(default_plans_dir)}"
[[ -d "$PLANS_DIR" ]] || die_usage "plans dir not found: $PLANS_DIR"

INDEX="$PLANS_DIR/INDEX.md"

# stat -c %Y (GNU) / stat -f %m (BSD/macOS)
mtime_epoch() {
    local e
    e="$(stat -c %Y "$1" 2>/dev/null || stat -f %m "$1" 2>/dev/null)" \
        || die_usage "failed to stat: $1"
    printf '%s' "$e"
}

# epoch -> "YYYY-MM-DD HH:MM" UTC (GNU -d @epoch / BSD -r epoch)
epoch_to_utc() {
    if date -u -d "@0" +"%s" >/dev/null 2>&1; then
        date -u -d "@$1" +"%Y-%m-%d %H:%M"
    else
        date -u -r "$1" +"%Y-%m-%d %H:%M"
    fi
}
# Build a TSV stream: epoch \\t name \\t title \\t status \\t done \\t total \\t has_exec \\t mtime_iso
# then sort numerically by epoch desc and render the markdown table.
collect_stream() {
    local f name epoch title status done total has_exec mtime_iso
    for f in "$PLANS_DIR"/*.md; do
        [[ -f "$f" ]] || continue
        name="$(basename "$f")"
        [[ "$name" == "INDEX.md" ]] && continue
        [[ "$name" == *.reviews.md ]] && continue

        epoch="$(mtime_epoch "$f")"
        mtime_iso="$(epoch_to_utc "$epoch")"
        title="$(awk '/^# / {sub(/^# +/, ""); print; exit}' "$f")"
        [[ -n "$title" ]] || title="(no title)"
        status="$(awk '/^Status:/ {sub(/^Status: +/, ""); print; exit}' "$f")"

        total="$(grep -cE '^[[:space:]]*(-|\*|[A-Za-z]?[0-9]+\.)[[:space:]]+\[[ x]\]' "$f" || true)"
        done="$(grep -cE '^[[:space:]]*(-|\*|[A-Za-z]?[0-9]+\.)[[:space:]]+\[x\]' "$f" || true)"

        if grep -qE '^## Execution Record' "$f"; then has_exec="yes"; else has_exec="no"; fi

        printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
            "$epoch" "$name" "$title" "${status:-—}" "$done" "$total" "$has_exec" "$mtime_iso"
    done
}

{
    echo "# Plans Index"
    echo
    echo "Auto-generated by \`scripts/plans-index.sh\` — do not edit; regenerate instead."
    echo "Sorted by mtime (newest first). Times UTC."
    echo
    echo "| Plan | Title | Status | Checkboxes | Execution Record | Modified (UTC) |"
    echo "|---|---|---|---|---|---|"
    collect_stream | sort -t$'\t' -k1,1rn | awk -F'\t' '
        { gsub(/\|/, "\\|", $2); gsub(/\|/, "\\|", $3); gsub(/\|/, "\\|", $4);
          printf "| `%s` | %s | %s | %s/%s | %s | %s |\n", $2, $3, $4, $5, $6, $7, $8 }'
} > "$INDEX.tmp" && mv "$INDEX.tmp" "$INDEX"

echo "wrote $INDEX"
